export const TOGGLE_NEW_HIVE_FORM_MODAL = "TOGGLE_NEW_HIVE_FORM_MODAL";
export const TOGGLE_NEW_BEE_FORM_MODAL = "TOGGLE_NEW_BEE_FORM_MODAL";
export const NEW_MARKER = "NEW_MARKER";
export const PREPARE_NEW_MARKER = "PREPARE_NEW_MARKER";
export const SET_MARKERS = "SET_MARKERS";
